- hosts: host1
  vars:
    service_1_value: "{{ deployer_service_1_value }}"
  roles:
    - role: service1
      tags: service1

- hosts: host2
  vars:
    service_2_value: "{{ deployer_service_2_value }}"
  roles:
    - role: service2
      tags: service2
